language: node_js
sudo: true

before_install:
- sudo apt-get update -qq

install:
- sudo apt-get install fuse appstream appstream-util git jq patch wget unzip

before_script:
- wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-i386.AppImage -O linuxdeploy; chmod +x linuxdeploy
- wget https://dl.discordapp.net/apps/linux/0.0.12/discord-0.0.12.tar.gz
- wget https://github.com/iteufel/nwjs-ffmpeg-prebuilt/releases/download/0.45.1/0.45.1-linux-x64.zip
- wget https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/exec-x86_64.so
# unpacking
- tar xzf discord-*.tar.gz
- unzip 0.45.1-linux-x64.zip

script:
- BUILD_SRC=$(pwd)
- mkdir AppDir
- APPDIR="${BUILD_SRC}/AppDir"
- mkdir -p "${APPDIR}/usr/share/applications"
- cp discord.desktop "${APPDIR}/usr/share/applications"
- mkdir -p "${APPDIR}/usr/share/icons/hicolor/scalable/apps"
- cp discord.svg "${APPDIR}/usr/share/icons/hicolor/scalable/apps"
- mkdir -p "${APPDIR}/usr/share/metainfo"
- cp com.discordapp.appdata.xml "${APPDIR}/usr/share/metainfo"
- mkdir -p "${APPDIR}/usr/share"
- cp -r Discord "${APPDIR}/usr/share/Discord"
- cd "${APPDIR}/usr/bin"
- ln -s ../share/Discord/Discord Discord
- cd "${BUILD_SRC}"
# Configuring
- cp exec-x86_64.so "${APPDIR}/usr/exec.so"
- cp libffmpeg.so "${APPDIR}/usr/libffmpeg.so"
# Building
- |
  ./linuxdeploy --appdir="${APPDIR}" --desktop-file="${APPDIR}/usr/share/applications/discord.desktop" \
  --output=appimage

after_success:
- wget https://github.com/probonopd/uploadtool/raw/master/upload.sh; chmod +x upload.sh
- bash upload.sh ./*.AppImage*
